export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="simple"
DISABLE_AUTO_UPDATE="true"

# Default zsh plugins
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Aliases
source $HOME/.aliases

# Editor
export EDITOR=$(which vim)
