export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME=""
DISABLE_AUTO_UPDATE="true"

# Default zsh plugins
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Aliases
source $HOME/.aliases

# Editor
export EDITOR=$(which vim)

# Pure prompt
fpath+=($HOME/.zsh/pure)
autoload -U promptinit; promptinit
prompt pure
